title: "Hernan Avalle"
author: "Hernan Avalle"
description: "My personal blog"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
#excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: true          # show article previews on the home page instead of headlines
date_format: "%d/%b/%Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
minimal_theme: false         # radically minimalistic theme
darkheader: true

# Pagination settings
paginate: 3
paginate_path: "/page:num/"

navigation:                  # show navigation links in the header
  - index.html
  - about.md

icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  envelope: "mailto:havalle@gmail.com"
  github: "https://github.com/havalle"
#  feed: ""

plugins: 
 - jekyll-feed
 - jekyll-default-layout
 - jekyll-paginate
